### ISSUE TITLE
DRY, button clones?

### ISSUE THREAD

**Issue by Stefan-Espant** [Akikosophia/look-and-feel-corporate-identity#1]
In de style.css zie ik twee classes met exact dezelfde styling. Check of dit kan worden geminimaliseerd tot 1 setting. Dit zal ongetwijfeld 10 regels css besparen.

https://github.com/Akikosophia/look-and-feel-corporate-identity/blob/20e0f588171f23989a4e930fdd17bf9718a4d278/style.css#L69-L91

**Comment by Akikosophia** [comment]
<img width="391" alt="Scherm­afbeelding 2023-11-30 om 12 13 04" src="https://github.com/Akikosophia/look-and-feel-corporate-identity/assets/144008863/5ccb9c29-985a-4da1-a9ad-c568b75e27cc">

Aangepast!
