### ISSUE TITLE
Ordered list huis info

### ISSUE THREAD

**Issue by Stefan-Espant** [Akikosophia/look-and-feel-corporate-identity#2]
Zit er een reden achter dat hier een ordered list word gebruikt? Is <ul> ook een optie?

https://github.com/Akikosophia/look-and-feel-corporate-identity/blob/20e0f588171f23989a4e930fdd17bf9718a4d278/index.html#L93-L96

**Comment by Akikosophia** [comment]
<img width="407" alt="Scherm­afbeelding 2023-11-30 om 12 16 44" src="https://github.com/Akikosophia/look-and-feel-corporate-identity/assets/144008863/deb3e652-a419-4e5a-ba6f-d1e80fe5ab54">

Aangepast!
